// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzelDers.DAL;

namespace OzelDers.DAL.Migrations
{
    [DbContext(typeof(OzelDersContext))]
    partial class OzelDersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OzelDers.ENT.Entities+AraTablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DersKonusuId");

                    b.Property<int>("EgitmenId");

                    b.HasKey("Id");

                    b.HasIndex("DersKonusuId");

                    b.HasIndex("EgitmenId");

                    b.ToTable("AraTablo");
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+DersAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.HasKey("Id");

                    b.ToTable("DersAlani");
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+DersKonusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<int>("DersAlaniId");

                    b.HasKey("Id");

                    b.HasIndex("DersAlaniId");

                    b.ToTable("DersKonusu");
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+Egitmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<decimal>("Fiyat");

                    b.Property<int>("IlceId");

                    b.Property<string>("Ozgecmis");

                    b.Property<double>("TelefonNo");

                    b.HasKey("Id");

                    b.HasIndex("IlceId");

                    b.ToTable("Egitmen");
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.HasKey("Id");

                    b.ToTable("Il");
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<int>("IlId");

                    b.HasKey("Id");

                    b.HasIndex("IlId");

                    b.ToTable("Ilce");
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+AraTablo", b =>
                {
                    b.HasOne("OzelDers.ENT.Entities+DersKonusu", "DersKonusu")
                        .WithMany("AraTablo")
                        .HasForeignKey("DersKonusuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OzelDers.ENT.Entities+Egitmen", "Egitmen")
                        .WithMany("AraTablo")
                        .HasForeignKey("EgitmenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+DersKonusu", b =>
                {
                    b.HasOne("OzelDers.ENT.Entities+DersAlani", "DersAlani")
                        .WithMany("DersKonusu")
                        .HasForeignKey("DersAlaniId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+Egitmen", b =>
                {
                    b.HasOne("OzelDers.ENT.Entities+Ilce", "Ilce")
                        .WithMany("Egitmen")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OzelDers.ENT.Entities+Ilce", b =>
                {
                    b.HasOne("OzelDers.ENT.Entities+Il", "Il")
                        .WithMany("Ilce")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
